name: MATLAB CI
on:
  push: { branches: [ "main", "master" ] }
  pull_request: { branches: [ "main", "master" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
      - name: Run tests
        uses: matlab-actions/run-command@v2
        with:
          command: "rng(0,'twister'); addpath('ecg'); run('tests/run_all_tests.m');"
